version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lumen
      MYSQL_USER: andre
      MYSQL_PASSWORD: password
    networks:
      dev_net:
        ipv4_address: 10.1.0.100
      web:
      default:

  nginx:
    container_name: nginx
    build: docker/nginx
    command: nginx -g "daemon off;"
    volumes:
      - ./:/var/www/html/app
    links:
      - php
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      dev_net:
        ipv4_address: 10.1.0.101
      web:
      default:

  php:
    container_name: php
    build: docker/php
    volumes:
      - ./:/var/www/html/app
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - mysql
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      dev_net:
        ipv4_address: 10.1.0.102
      web:
      default:

# Docker Networks
networks:
  web:
    driver: bridge
  dev_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
